package br.yuh.entidades;

public class DadosSchemaXml {
	public static String solicitacaoProcedimento = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
			+ "<?xml version=\"1.0\" standalone=\"yes\"?>\r\n"
			+ "<solicitacaoProcedimentoWS xmlns=\"http://www.ans.gov.br/padroes/tiss/schemas\" xmlns:ns2=\"http://www.w3.org/2000/09/xmldsig#\">\r\n"
			+ "  <cabecalho>\r\n"
			+ "    <identificacaoTransacao>\r\n"
			+ "      <tipoTransacao>SOLICITACAO_PROCEDIMENTOS</tipoTransacao>\r\n"
			+ "      <sequencialTransacao>3302001050</sequencialTransacao>\r\n"
			+ "      <dataRegistroTransacao>2024-06-13</dataRegistroTransacao>\r\n"
			+ "      <horaRegistroTransacao>07:19:04</horaRegistroTransacao>\r\n"
			+ "    </identificacaoTransacao>\r\n"
			+ "    <origem>\r\n"
			+ "      <identificacaoPrestador>\r\n"
			+ "        <CNPJ>04559855000108</CNPJ>\r\n"
			+ "      </identificacaoPrestador>\r\n"
			+ "    </origem>\r\n"
			+ "    <destino>\r\n"
			+ "      <registroANS>123456</registroANS>\r\n"
			+ "    </destino>\r\n"
			+ "    <Padrao>4.01.00</Padrao>\r\n"
			+ "  </cabecalho>\r\n"
			+ "  <solicitacaoProcedimento>\r\n"
			+ "    <solicitacaoInternacao>\r\n"
			+ "      <registroANS>123456</registroANS>\r\n"
			+ "      <numeroGuiaPrestador>3302001050</numeroGuiaPrestador>\r\n"
			+ "      <tipoEtapaAutorizacao>2</tipoEtapaAutorizacao>\r\n"
			+ "      <dadosBeneficiario>\r\n"
			+ "        <numeroCarteira>0560100151000010</numeroCarteira>\r\n"
			+ "        <atendimentoRN>N</atendimentoRN>\r\n"
			+ "      </dadosBeneficiario>\r\n"
			+ "      <identificacaoSolicitante>\r\n"
			+ "        <dadosDoContratado>\r\n"
			+ "          <cnpjContratado>04559855000108</cnpjContratado>\r\n"
			+ "        </dadosDoContratado>\r\n"
			+ "        <dadosProfissionalContratado>\r\n"
			+ "          <nomeProfissional>HOSPITAL GERAL</nomeProfissional>\r\n"
			+ "          <conselhoProfissional>06</conselhoProfissional>\r\n"
			+ "          <numeroConselhoProfissional>3716</numeroConselhoProfissional>\r\n"
			+ "          <UF>27</UF>\r\n"
			+ "          <CBOS>225250</CBOS>\r\n"
			+ "        </dadosProfissionalContratado>\r\n"
			+ "      </identificacaoSolicitante>\r\n"
			+ "      <dadosHospitalSolicitado>\r\n"
			+ "        <codigoIndicadonaOperadora>00000802</codigoIndicadonaOperadora>\r\n"
			+ "        <nomeContratadoIndicado>HOSPITAL GERAL</nomeContratadoIndicado>\r\n"
			+ "        <dataSugeridaInternacao>2024-06-28</dataSugeridaInternacao>\r\n"
			+ "      </dadosHospitalSolicitado>\r\n"
			+ "      <dadosInternacao>\r\n"
			+ "        <caraterAtendimento>2</caraterAtendimento>\r\n"
			+ "        <tipoInternacao>2</tipoInternacao>\r\n"
			+ "        <regimeInternacao>1</regimeInternacao>\r\n"
			+ "        <qtDiariasSolicitadas>10</qtDiariasSolicitadas>\r\n"
			+ "        <indicadorOPME>N</indicadorOPME>\r\n"
			+ "        <indicadorQuimio>N</indicadorQuimio>\r\n"
			+ "        <indicacaoClinica>1</indicacaoClinica>\r\n"
			+ "      </dadosInternacao>\r\n"
			+ "      <hipotesesDiagnosticas>\r\n"
			+ "        <diagnosticoCID>A511</diagnosticoCID>\r\n"
			+ "        <indicadorAcidente>2</indicadorAcidente>\r\n"
			+ "      </hipotesesDiagnosticas>\r\n"
			+ "      <procedimentosSolicitados>\r\n"
			+ "        <procedimento>\r\n"
			+ "          <codigoTabela>22</codigoTabela>\r\n"
			+ "          <codigoProcedimento>31003796</codigoProcedimento>\r\n"
			+ "          <descricaoProcedimento>RETOSSIGMOIDECTOMIA ABDOMINAL POR</descricaoProcedimento>\r\n"
			+ "        </procedimento>\r\n"
			+ "        <quantidadeSolicitada>1</quantidadeSolicitada>\r\n"
			+ "      </procedimentosSolicitados>\r\n"
			+ "      <dataSolicitacao>2024-06-13</dataSolicitacao>\r\n"
			+ "      <observacao>TESTE NOVO TISS</observacao>\r\n"
			+ "      <anexoClinico>\r\n"
			+ "        <solicitacaoQuimioterapia>\r\n"
			+ "          <cabecalhoAnexo>\r\n"
			+ "            <registroANS>123456</registroANS>\r\n"
			+ "            <numeroGuiaAnexo>2002001052</numeroGuiaAnexo>\r\n"
			+ "            <numeroGuiaReferenciada>2002001050</numeroGuiaReferenciada>\r\n"
			+ "            <numeroGuiaOperadora>13318585</numeroGuiaOperadora>\r\n"
			+ "            <dataSolicitacao>2024-06-13</dataSolicitacao>\r\n"
			+ "            <senha>13318585</senha>\r\n"
			+ "            <dataAutorizacao>2024-06-13</dataAutorizacao>\r\n"
			+ "          </cabecalhoAnexo>\r\n"
			+ "          <dadosBeneficiario>\r\n"
			+ "            <numeroCarteira>0560100151000010</numeroCarteira>\r\n"
			+ "            <atendimentoRN>N</atendimentoRN>\r\n"
			+ "          </dadosBeneficiario>\r\n"
			+ "          <dadosComplementaresBeneficiario>\r\n"
			+ "            <peso>80</peso>\r\n"
			+ "            <altura>1.60</altura>\r\n"
			+ "            <superficieCorporal>10</superficieCorporal>\r\n"
			+ "            <idade>30</idade>\r\n"
			+ "            <sexo>M</sexo>\r\n"
			+ "          </dadosComplementaresBeneficiario>\r\n"
			+ "          <medicoSolicitante>\r\n"
			+ "            <nomeProfissional>MEDICO SOLICITANTE</nomeProfissional>\r\n"
			+ "            <telefoneProfissional>43-3001-1234</telefoneProfissional>\r\n"
			+ "          </medicoSolicitante>\r\n"
			+ "          <diagnosticoOncologicoQuimioterapia>\r\n"
			+ "            <diagQuimio>\r\n"
			+ "              <diagnosticoCID>01</diagnosticoCID>\r\n"
			+ "              <estadiamento>1</estadiamento>\r\n"
			+ "              <finalidade>1</finalidade>\r\n"
			+ "              <ecog>?</ecog>\r\n"
			+ "            </diagQuimio>\r\n"
			+ "            <tumor>1</tumor>\r\n"
			+ "            <nodulo>1</nodulo>\r\n"
			+ "            <metastase>1</metastase>\r\n"
			+ "            <tipoQuimioterapia>1</tipoQuimioterapia>\r\n"
			+ "            <planoTerapeutico>1</planoTerapeutico>\r\n"
			+ "          </diagnosticoOncologicoQuimioterapia>\r\n"
			+ "          <drogasSolicitadas>\r\n"
			+ "            <drogaSolicitada>\r\n"
			+ "              <dataProvavel>2024-01-09</dataProvavel>\r\n"
			+ "              <identificacao>\r\n"
			+ "                <codigoTabela>20</codigoTabela>\r\n"
			+ "                <codigoProcedimento>90274857</codigoProcedimento>\r\n"
			+ "                <descricaoProcedimento>DIPIRONA SODICA + CLORIDRATO DE ADIFENINA </descricaoProcedimento>\r\n"
			+ "              </identificacao>\r\n"
			+ "              <qtDoses>1</qtDoses>\r\n"
			+ "              <unidadeMedida>1</unidadeMedida>\r\n"
			+ "              <viaAdministracao>1</viaAdministracao>\r\n"
			+ "              <frequencia>1</frequencia>\r\n"
			+ "            </drogaSolicitada>\r\n"
			+ "          </drogasSolicitadas>\r\n"
			+ "          <numeroCiclos>2</numeroCiclos>\r\n"
			+ "          <cicloAtual>1</cicloAtual>\r\n"
			+ "          <diasCicloAtual>1</diasCicloAtual>\r\n"
			+ "          <intervaloCiclos>1</intervaloCiclos>\r\n"
			+ "        </solicitacaoQuimioterapia>\r\n"
			+ "      </anexoClinico>\r\n"
			+ "    </solicitacaoInternacao>\r\n"
			+ "  </solicitacaoProcedimento>\r\n"
			+ "  <hash>D9F57B4680F0412A1225A5B7BE330092</hash>\r\n"
			+ "</solicitacaoProcedimentoWS>\r\n"
			+ "";
}
